# Change these first
owner: EKG-Gniebel-Ruebgarten # Your GitHub organization or username, where this repository lives
repo: website-uptime # The name of this repository

sites:
  - name: EKG Gniebel Rübgarten
    url: https://neu.ekg-gniebel-ruebgarten.de
  - name: EKG Gniebel Rübgarten (falsch)
    url: https://neue.eeekg-gniebel-ruebgarten.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /website-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Website-Status
  introTitle: "Diese **Statusseite** zeigt an, ob unsere Website erreichbar ist."
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Zu unserer Seite
      href: https://ekg-gniebel-ruebgarten.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Aktive Probleme
  allSystemsOperational: Alle Systeme funktionieren
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS Posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Gelöst
  incidentOngoing: Aktuell
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentSubscribe: Updates abonnieren
  incidentViewOnGitHub: Auf GitHub anschauen
  incidentCommentSummary: Gepostet am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Incidents
  pastIncidents: Vorherige Incidents
  pastIncidentsResolved: In $MINUTES minuten mit $POSTS Posts gelöst
  liveStatus: Live-Status
  overallUptime: "Gesamte Uptime: $UPTIME"
  overallUptimeTitle: Gesamte Uptime
  averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Antwortzeit
  sevelDayResponseTime: 7-Tage durchschnittliche Antwortzeit
  responseTimeMs: Antwortzeit (ms)
  up: Funktioniert
  down: Down
  degraded: Eingeschränkt
  ms: ms
  loading: Lädt
  navGitHub: GitHub
  footer: Diese Seite ist [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit überschritten
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Token entfernen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Ein Fehler ist aufgetreten
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Zur Homepage
  pastScheduledMaintenance: Vergangene angekündigte Wartungen
  scheduledMaintenance: Angekündigte Wartungen
  scheduledMaintenanceSummaryStarted: Gestartet am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Startet am $DATE für $DURATION Minuten
  startedAt: Gestartet am/um
  startsAt: Startet am/um
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Fertiggestellt
  incidentScheduled: Geplant
